// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0VN8gUbkEUN67J8jU1hGZ_wYR1Sr4ngw',
    appId: '1:238444674039:web:828cb6ba08af96b1d80cf2',
    messagingSenderId: '238444674039',
    projectId: 'auth-example-b74bb',
    authDomain: 'auth-example-b74bb.firebaseapp.com',
    storageBucket: 'auth-example-b74bb.appspot.com',
    measurementId: 'G-Y982B7BP15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr6WhqEx9ltK1foEs1BnZqekgDa8lVoB4',
    appId: '1:238444674039:android:32301c1b116b6723d80cf2',
    messagingSenderId: '238444674039',
    projectId: 'auth-example-b74bb',
    storageBucket: 'auth-example-b74bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXbiw9m5VPL_H3YNcF1vqiRIuRsmjDJs',
    appId: '1:238444674039:ios:77f58478a1f23ad2d80cf2',
    messagingSenderId: '238444674039',
    projectId: 'auth-example-b74bb',
    storageBucket: 'auth-example-b74bb.appspot.com',
    iosClientId:
        '238444674039-eb8gadtthrakkcqaah9oau83923mgt8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRXbiw9m5VPL_H3YNcF1vqiRIuRsmjDJs',
    appId: '1:238444674039:ios:77f58478a1f23ad2d80cf2',
    messagingSenderId: '238444674039',
    projectId: 'auth-example-b74bb',
    storageBucket: 'auth-example-b74bb.appspot.com',
    iosClientId:
        '238444674039-eb8gadtthrakkcqaah9oau83923mgt8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample',
  );
}
